# Generated by Django 3.2.4 on 2021-06-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateField(auto_now=True, verbose_name='updated')),
                ('waste_type', models.CharField(choices=[('JK', 'Junk'), ('VG', 'Vegetal'), ('CM', 'Construction Material'), ('VP', 'Vehicle parts')], max_length=50, verbose_name='waste_type')),
                ('location', models.JSONField(verbose_name='location')),
                ('reported_by', models.EmailField(max_length=254, verbose_name='reported_by')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=240, verbose_name='name')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateField(auto_now=True, verbose_name='updated')),
                ('geometry', models.JSONField(verbose_name='geometry')),
            ],
        ),
    ]
